[tool.poetry]
name = "distillm"
version = "0.0.1"
description = ""
authors = ["davidberenstein1957 <david.m.berenstein@gmail.com>"]
readme = "README.md"
packages = [{include = "distillm"}]

[tool.poetry.dependencies]
python = "^3.8"
llama-cpp-python = "^0.2.11"
transformers = "^4.34.1"
datasets = "^2.14.5"

[tool.poetry.group.dev.dependencies]
pytest = "^7.3.2"
ruff = "^0.0.272"
black = "^23.3.0"
pre-commit = "^3.3.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

