[tool.poetry]
name = "nebula_py"
version = "0.3.0"
description = ""
authors = ["lone_druid <enikita332@gmail.com>"]
readme = "README.md"
packages = [{include = "nebula", from = "src"}]
repository = "https://github.com/NikitaNightBot/Nebula"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
line-length = 320
ignore = ["E741", "E701"]

