[tool.poetry]
name = "axdocsystem"
version = "0.1.16"
description = "a simple document managment system, was created for the purpose of submitting a work for uni"
authors = ["axdjuraev <axdjuraev@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
axsqlalchemy = "0.0.54"
fastapi = "0.91.0,"
fastapi-jwt-auth = "0.5.0,"
fastapi-pagination = "0.11.4"
uvicorn = {extras = ["standart"], version = "^0.23.2"}
python-dotenv = "0.21.1"
aiosqlite = "^0.19.0"
aiofiles = "^23.2.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
