[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "openframe_criteria_set_protocol"
version = "0.0.20"
authors = [
    { name="AndrÃ©s Angulo", email="aa@openframe.org" },
]
description = "A protocol and tools for defining and working with criteria sets"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/Frame-ApS/criteria-set-protocol"
"Bug Tracker" = "https://github.com/Frame-ApS/criteria-set-protocol/issues"
