pages:
  artifacts:
    paths:
    - public
  image: sphinxdoc/sphinx
  only:
  - main
  script:
  - bash ./scripts/build_documentation.sh -i public
  stage: deploy
  tags:
  - ci.inria.fr
  - linux
  - small
release_job:
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  release:
    description: Release $CI_COMMIT_TAG
    tag_name: $CI_COMMIT_TAG
  rules:
  - if: $CI_COMMIT_TAG
  script:
  - echo "running release_job"
  stage: release
  tags:
  - ci.inria.fr
  - linux
  - small
stages:
- test
- release
- deploy
test:
  image: python:latest
  script:
  - bash ./scripts/test.sh
  stage: test
  tags:
  - ci.inria.fr
  - linux
  - small
