[tool.poetry]
name = "mt5connect"
version = "0.3.0"
description = ""
authors = ["Alpha <piotr@piotryordanov.com>"]
readme = "README.md"

[tool.poetry.dependencies]
pandas = "^2.0.3"
numpy = "^1.24.4"
pyarrow = "^13.0.0"
python = "^3.11"
boto3 = "^1.28.37"
pytest-watcher = "^0.3.4"
pytest = "^7.4.0"
requests = "^2.31.0"
psutil = "^5.9.6"
opensearch-py = "^2.3.2"
build = "^1.0.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.pytest-watcher]
now = true
runner = "pytest"
runner_args = []
patterns = ["*.py"]
ignore_patterns = []
