[tool.poetry]
name = "sigan"
version = "0.1.14"
description = "architecture update"
authors = ["Earthquakoo <cream5343@gmail.com>"]
readme = "README.md"

[tool.poetry.scripts]
sigan = "sigan.src.commands.command:app"

[tool.poetry.dependencies]
python = "^3.9"
typer = {extras = ["all"], version = "^0.9.0"}
python-dotenv = "^1.0.0"
rich = "^13.6.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
