[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dotalib"
version = "0.0.3"
authors = [
  { name="classno", email="classno@gmail.com" },
]
description = "dotalib"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/classno/dotalib"
"Bug Tracker" = "https://github.com/classno/dotalib/issues"