[tool.black]
target-version = ['py38']
line-length = 99
exclude = '''
(
  /(
      \.eggs
    | \.git
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
    | venv
  )/
)
'''

[tool.isort]
profile = "black"

[tool.poetry]
name = "ztrack"
version = "1.2.0"
description = ""
authors = ["Ka Chung Lam <kclamar@connect.ust.hk>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/kclamar/ztrack"
repository = "https://github.com/kclamar/ztrack"
classifiers=[
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: MIT License",
    "Operating System :: Microsoft :: Windows",
    "Intended Audience :: Science/Research"
]

[tool.poetry.dependencies]
python = "^3.8"
click = "^8.0.1"
decord = "^0.6.0"
matplotlib = "^3.4.2"
opencv-python = "^4.5.2"
pandas = "^1.3.0"
PyQt5 = "^5.10.1"
pyqtgraph = "^0.12.2"
qtmodern = "^0.2.0"
scikit-image = "^0.18.2"
superqt = "^0.3"
tables = "^3.8.0"
tqdm = "^4.61.2"

bump2version = { version = "*", optional = true }
pandas-stubs = { version = "*", optional = true }
pre-commit = { version = "*", optional = true }
PyQt5-stubs = { version = "*", optional = true }

[tool.poetry.extras]
dev = [
    "bump2version",
    "pandas-stubs",
    "pre-commit",
    "PyQt5-stubs",
]

[tool.poetry.scripts]
ztrack = "ztrack.cli:main"

[build-system]
requires = [
    "poetry-core>=1.0.0",
    "setuptools>=57.0.0",
]

build-backend = "poetry.core.masonry.api"
