[build-system]
requires = ["setuptools>=61.0"]

build-backend = "setuptools.build_meta"

[project]
name = "simtwin"
version = "0.0.44"
description = "Simtwin allows to exchange simulation data with a remote simulation server by automatically crating twins of the users created objects on the server."
dependencies = [
    "gmsh >= 4.10.5",
    "matplotlib >= 3.6.1",
    "numpy >= 1.23.3",
    "rootpath >= 0.1.1"
]
license = {file = "LICENSE"}
authors = [
    {name = "Henrik Stromberg", email="henrik@askdrq.com"}
]

[project.urls]
homepage = "https://askdrq.com"

[tool.poetry]
# ...
packages = [
    { include = "src/simtwin" },
]