[build-system]
requires      = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pybrams"
version = "0.0.7"
description = "BRAMS"
readme = "README.md"
authors = [{ name = "Antoine Calegaro", email = "antoine.calegaro@aeronomie.be" }]
license = { file = "LICENSE" }
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
]
keywords = ["brams", "meteor"]
dependencies = [
    "requests",
    "numpy",
    "scipy",
	"json-fix",
    "matplotlib"
]
requires-python = ">=3.6"

[project.urls]
Homepage = "https://brams.aeronomie.be"
Git = "https://gitlab.aeronomie.be/ae/brams/pybrams"
