


#
#	HOW TO PUBLISH:
#
#		(rm -rf dist && python3 -m build --sdist && twine upload dist/*)
#

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "REVENUE"
version = "0.0.4"
description = "online academy building resources"
readme = "revenue.txt"
dependencies = [
	"chameleon",
	"flask"
]

#
#	https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#setuptools-specific-configuration
#
#[tool.setuptools]
#script-files = [ "lands/scripts/revenue" ]

#
#	https://setuptools.pypa.io/en/latest/userguide/pyproject_config.html#setuptools-specific-configuration
#
[project.scripts]
revenue = "revenue.clique:start"

[tool.setuptools.packages.find]
where = [ "lands/structures" ]

#
#	https://setuptools.pypa.io/en/latest/userguide/datafiles.html
#
[tool.setuptools.package-data]
"*" = [ "*.HTML" ]