[build-system]
requires = ["setuptools", "wheel"]

[project]
name = "django_print_models"
version = "0.4"
authors = [
  { name = "Mitchel Humpherys", email = "mitch.special@gmail.com" },
]
description = "A Django package to print trimmed down models for easier sharing."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3"
dependencies = [
  "django>=3.0"
]
keywords = ["django"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: Django",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
]

[project.urls]
"Homepage" = "https://github.com/mgalgs/django_print_models"
"Bug Tracker" = "https://github.com/mgalgs/django_print_models/issues"
