[tool.poetry]
name = "nlp-data"
version = "0.1.8"
description = "普强内部NLP数据存储分享工具"
authors = ["wang mengdi <wangmengdi@pachiratech.com>"]
readme = "README.md"
packages = [{include = "nlp_data"}]

[tool.poetry.dependencies]
python = "^3.7"
datasets = ">=2.14.1"
docarray = {"extras" = ["aws"], version = ">=0.39"}
boto3 = ">=1.28.8"
openpyxl = ">=3.1.2"
pandas = ">=1.3.2"
wasabi = ">=1.1.1"
tqdm = ">=4.65.0"
rich = ">=13.4.2"
pydantic = ">=1.10.12"
srsly = ">=2.4.6"
openai = ">=0.27.1"

[tool.poetry.scripts]
nlp-data = "nlp_data.cli:main"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
