[tool.poetry]
name = "mongodb_python_manager"
version = "1.7.0"
description = ""
authors = ["ldom <louis@giron-dom.eu>"]
readme = "README.md"
packages = [{include = "mongodb_python_manager"}]


[tool.poetry.dependencies]
python = ">=3.9,<3.13"
dnspython = "^2.4.2"
exceptiongroup = "^1.1.3"
pytest = "^7.4.1"
python-dotenv = "^1.0.0"
structlog = "^23.1.0"
tqdm = "^4.66.1"
pymongo = "^4.5.0"
motor = "^3.3.1"
pandas = "^2.1.1"

[tool.poetry.group.dev.dependencies]
black = "^23.10.0"
coverage = "^7.3.2"
pre-commit = "^3.5.0"

[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pytest-runner",
    "setuptools_scm",
]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
target-version = ["py38", "py39", "py310"]
