[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.poetry]
include = ["serverseeker.exe"]

[project]
name = "serverseeker"
version = "1.0.2"
authors = [
    {name="Igyeom Park", email="hi@ians.site"},
]
description = "A Python wrapper for the ServerSeeker API. This is a CLI to work with ServerSeeker, a tool to scan for Minecraft servers. Visit serverseeker.net for more info."
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"GitHub Repo" = "https://github.com/Igyeom/ServerSeeker"
"ServerSeeker Discord" = "https://serverseeker.net"
"ServerSeeker Documentation" = "https://serverseeker.net/docs"