[project]
name = "apix"
version = "0.0.0dev1"
description = ""
authors = [
    { name = "Arwichok", email = "arwichok@gmail.com" },
]
dependencies = []
requires-python = ">=3.8"
readme = "README.md"

[project.license]
text = "MIT"

[project.optional-dependencies]
base = [
    "msgspec>=0.18.4",
]

[project.scripts]
apix = "apix.cli:main"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm.scripts]
test = "pytest"
mypy = "mypy src"
ruff = "ruff src"
ruff_fix = "ruff --fix src"

[tool.pdm.scripts.apix]
call = "apix.cli:main"

[tool.pdm.dev-dependencies]
lint = [
    "mypy>=1.6.0",
    "ruff>=0.0.292",
]
test = [
    "pytest>=7.4.2",
    "msgspec>=0.18.4",
]

[tool.mypy]
ignore_missing_imports = true
