[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "sop_deutils"
version = "0.3.4"
authors = [
  { name="liuliukiki aka clong", email="longnc@yes4all.com" },
]
description = "A utils package for Yes4All SOP"
readme = "test.rst"
requires-python = ">=3.7"
dependencies = ["openpyxl >= 3.1.2","pytz >= 2023.3", "pandas >= 2.1.1", "python-telegram-bot >= 20.6", "SQLAlchemy >= 2.0.21", "lxml >= 4.9.3", "gspread >= 5.11.3", "psycopg2-binary >= 2.9.9", "minio >= 7.1.17", "pyarrow >= 13.0.0", "requests >= 2.31.0", "aiofiles >= 23.2.1", "fastparquet >= 2023.8.0", "mysql-connector-python >= 8.0.33"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Author_Github" = "https://github.com/dribblewithclong"
