[build-system]
requires = ["hatchling", "numpy", "wavio", "playsound"]
build-backend = "hatchling.build"

[project]
name = "morsey"
version = "0.1.1"
authors = [
  { name="Aaron Harnish", email="aaronjharnish@gmail.com" },
]
description = "Contains methods to translate morse code and english str objects."
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/AHarnishPM/morsey"
"Bug Tracker" = "https://github.com/AHarnishPM/morsey/issues"