[project]
name = "devboard"
version = "0.0.0"
description = "A development dashboard for your projects. Available to sponsors only."
authors = [{name = "TimothÃ©e Mazzucotelli", email = "pawamoy@pm.me"}]
readme = "README.md"
requires-python = ">=3.8"
classifiers = ["Development Status :: 1 - Planning"]
