[package]
name = "dpsa4fl-bindings"
version = "0.1.68"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "dpsa4fl_bindings"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.17", features = ["extension-module", "anyhow"] }
pyo3-asyncio = { version = "0.17", features = ["attributes", "tokio-runtime"] }
tokio = { version = "1.22", features = ["time"] }
async-std = "1.9"
dpsa4fl = { git = "https://github.com/dpsa-project/dpsa4fl", branch = "main" }
url = { version = "2.3.1" }
anyhow = "1.0"
fixed = "1.19"
fixed-macro = "1.1.1"
fraction = "0.13.1"
numpy = "0.17"
ndarray = "0.15"
