[tool.poetry]
name = "shrtcodes"
version = "1.2.0"
description = "Simple shortcodes for Python."
authors = ["Peter Byfield <byfield554@gmail.com>"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/Peter554/shrtcodes#readme"
repository = "https://github.com/Peter554/shrtcodes"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]
black = "^22.12.0"
mypy = "^0.991"
pytest = "^7.2.0"


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
