[tool.poetry]
name = "zit"
version = "0.0.5a3"
description = "ZitySpace CLI tool"
authors = ["Rui Zheng <rui@zityspace.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.9"
PyYAML = "^6.0"
typer = {extras = ["all"], version = "^0.7.0"}
httpx = {extras = ["socks"], version = "^0.24.1"}
websocket-client = "^1.5.1"
fastapi = "^0.95.1"
pandas = "^2.0.2"
duckdb = "^0.8.1"
pillow = "^9.5.0"
python-multipart = "^0.0.6"

[tool.poetry.group.dev.dependencies]
ipdb = "^0.13.13"
ipython = "^8.12.0"
black = "^23.3.0"
flake8 = "^6.0.0"
isort = "^5.12.0"
pre-commit = "^3.2.2"
commitizen = "^2.42.1"

[tool.poetry.scripts]
zit = "zit.main:app"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 120
exclude = '''
(
  /(
      dist
  )/
)
'''
preview = true

[tool.isort]
profile = "black"
skip = ["dist"]

[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.5a3"
version_files = ["pyproject.toml:version"]
tag_format = "v$version"
