[tool.poetry]
name = "oswdatamodel"
version = "0.0.4"
description = "Offshore wind turbine structure datamodel written in pydantic."
authors = ["Ben Cannell"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.4.2"
pytest = "^7.4.2"
black = "^23.9.1"

[tool.poetry.group.dev.dependencies]
pydantic = "^2.4.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
