[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "delayed-reactant-labeling"
version = "0.2.2"
authors = [
    {name="Martijn Dingemans", email="Martijn.Dingemans@ru.nl"},
    {name="Matthijs Hellinghuizen", email="matthijs.hellinghuizen@ru.nl"}
]
description = "A toolbox for analysis of Delayed Reactant Labeling experiments."
readme = "README.txt"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]