[tool.poetry]
name = "centopy"
version = "0.2.9"
description = "Python package for managing file creation and loading"
authors = ["Vagner Bessa <bessavagner@gmail.com>"]
license = "None"
readme = "README.md"
packages = [{include = "centopy", from = "src"}]
include = [
	{path = "src/app.py"},
	{path = "src/cli.py"},
	{path = "src/gui.py"},
	{path = "src/settings.py"}
]

[tool.poetry.dependencies]
python = "^3.10"
click = "^8.1.3"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
ipython = "^8.14.0"
notebook = "^7.0.0"
pytest = "^7.4.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
[tool.poetry.scripts]
centopy = "centopy.__main__:main"
